// <auto-generated />
using System;
using KosovaDoganaModerne.Te_dhenat;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KosovaDoganaModerne.Migrations
{
    [DbContext(typeof(AplikacioniDbKonteksti))]
    [Migration("20251201091151_AddImazhetProduktitTable")]
    partial class AddImazhetProduktitTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Dega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmriDeges")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eshte_Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KodiDeges")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Krijuar_Me")
                        .HasColumnType("TEXT");

                    b.Property<string>("Krijuar_Nga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Qyteti")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoni")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmriDeges");

                    b.HasIndex("Eshte_Aktiv");

                    b.HasIndex("KodiDeges")
                        .IsUnique();

                    b.ToTable("Deget");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.FormatPrintimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CssStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmriFormatit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KrijuarMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrijuarNga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlojiModulit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPosition")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaperSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PerditesomMe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormatetiPrintimit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.GlobalPrintFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVendosjes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatPrintimiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlojiModulit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifikuarMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifikuarNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pershkrimi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendosurNga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EshteAktiv");

                    b.HasIndex("FormatPrintimiId");

                    b.HasIndex("LlojiModulit")
                        .IsUnique();

                    b.ToTable("GlobalPrintFormats");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.HistoriaVlerave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresaIP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("AdresaIP");

                    b.Property<string>("ArsyejaE_Ndryshimit")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ArsyejaE_Ndryshimit");

                    b.Property<string>("FotoNdryshimit")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FotoNdryshimit");

                    b.Property<DateTime>("Ndryshuar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ndryshuar_Me");

                    b.Property<string>("Ndryshuar_Nga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Ndryshuar_Nga");

                    b.Property<int>("NumriVersionit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumriVersionit");

                    b.Property<string>("Valuta_Mepar")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Valuta_Mepar");

                    b.Property<string>("Valuta_Re")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Valuta_Re");

                    b.Property<int>("VleraProduktit_Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VleraProduktit_Id");

                    b.Property<decimal>("Vlera_Mepar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Vlera_Mepar");

                    b.Property<decimal>("Vlera_Re")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Vlera_Re");

                    b.HasKey("Id");

                    b.HasIndex("Ndryshuar_Me");

                    b.HasIndex("Ndryshuar_Nga");

                    b.HasIndex("VleraProduktit_Id");

                    b.ToTable("HistoriaVlerave");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.ImazhetProduktit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmriOrigjinal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("EmriOrigjinal");

                    b.Property<bool>("EshteImazhKryesor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EshteImazhKryesor");

                    b.Property<string>("LlojiImazhit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LlojiImazhit");

                    b.Property<long>("MadhesiaBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MadhesiaBytes");

                    b.Property<DateTime>("NgarkuarMe")
                        .HasColumnType("TEXT")
                        .HasColumnName("NgarkuarMe");

                    b.Property<string>("NgarkuarNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NgarkuarNga");

                    b.Property<string>("Pershkrimi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Pershkrimi");

                    b.Property<int>("RradhaShfaqjes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RradhaShfaqjes");

                    b.Property<string>("ShtegimaImazhit")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ShtegimaImazhit");

                    b.Property<int>("VleraProduktit_Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VleraProduktit_Id");

                    b.HasKey("Id");

                    b.HasIndex("EshteImazhKryesor");

                    b.HasIndex("LlojiImazhit");

                    b.HasIndex("VleraProduktit_Id");

                    b.ToTable("ImazhetProduktit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.KerkeseRegjistrim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArsetimiRefuzimit")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataKerkeses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataShqyrtimit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dega_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamenti")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmriDegës")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmriPlote")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteVerifikuarNeAD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KodiZyrtarit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozicioni")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShqyrtuesId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KerkesatRegjistrim");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Komenti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Krijuar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Krijuar_Me");

                    b.Property<string>("Krijuar_Nga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Krijuar_Nga");

                    b.Property<string>("Permbajtja")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Permbajtja");

                    b.Property<int>("VleraProduktitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VleraProduktitId");

                    b.HasKey("Id");

                    b.HasIndex("Krijuar_Me");

                    b.HasIndex("VleraProduktitId");

                    b.ToTable("Komentet");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.KomentiDeges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDergimit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataLeximit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPergjigjes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DergoPrejNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmriDeges")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteLexuar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EshteZgjidhur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KodiTarifar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LexoNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesazhi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pergjigja")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PergjigjetNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VleraProduktit_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataDergimit");

                    b.HasIndex("EmriDeges");

                    b.HasIndex("EshteLexuar");

                    b.HasIndex("EshteZgjidhur");

                    b.HasIndex("KodiTarifar");

                    b.HasIndex("VleraProduktit_Id");

                    b.ToTable("KomentetDegeve");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.NdryshimiTransportit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresaIP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArsyejaE_Ndryshimit")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cmimi_Mepar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cmimi_Ri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ndryshuar_Me")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ndryshuar_Nga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumriVersionit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShpenzimiTransportit_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valuta_Mepar")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valuta_Re")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ndryshuar_Me");

                    b.HasIndex("ShpenzimiTransportit_Id");

                    b.ToTable("NdryshimetTransportit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Njoftim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataLeximit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteLexuar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ikona")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Linku")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lloji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perdoruesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pershkrimi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataKrijimit");

                    b.HasIndex("EshteLexuar");

                    b.HasIndex("Lloji");

                    b.HasIndex("Perdoruesi");

                    b.ToTable("Njoftimet");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dega_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamenti")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmriPlote")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HyrjaEFundit")
                        .HasColumnType("TEXT");

                    b.Property<string>("KodiZyrtarit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pozicioni")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dega_Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.PreferencatPerdoruesit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KrijuarMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlojiPreferences")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PerditesomMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Perdoruesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vlera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PreferencatPerdoruesit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.PrintAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresaIP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrintimit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteSuksesshem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filtrat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormatPrintimiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormatiEksportimit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlojiRaportit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MesazhiGabimit")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumriRekordeve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Perdoruesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SesioniId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shenime")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataPrintimit");

                    b.HasIndex("FormatPrintimiId");

                    b.HasIndex("FormatiEksportimit");

                    b.HasIndex("LlojiRaportit");

                    b.HasIndex("Perdoruesi");

                    b.HasIndex("SesioniId");

                    b.ToTable("PrintAuditLogs");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.RegjistriAuditimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresaIP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("AdresaIP");

                    b.Property<string>("Detajet")
                        .HasColumnType("TEXT")
                        .HasColumnName("Detajet");

                    b.Property<string>("Entiteti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Entiteti");

                    b.Property<string>("Entiteti_Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Entiteti_Id");

                    b.Property<bool>("Eshte_Suksesshem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Eshte_Suksesshem");

                    b.Property<DateTime>("Koha")
                        .HasColumnType("TEXT")
                        .HasColumnName("Koha");

                    b.Property<string>("LlojiVeprimit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LlojiVeprimit");

                    b.Property<string>("MesazhiGabimit")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("MesazhiGabimit");

                    b.Property<string>("Perdoruesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Perdoruesi");

                    b.Property<string>("Sesioni_Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Sesioni_Id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserAgent");

                    b.Property<string>("Vlerat_Reja")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vlerat_Reja");

                    b.Property<string>("Vlerat_Vjetra")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vlerat_Vjetra");

                    b.HasKey("Id");

                    b.HasIndex("Entiteti");

                    b.HasIndex("Koha");

                    b.HasIndex("LlojiVeprimit");

                    b.HasIndex("Perdoruesi");

                    b.HasIndex("Sesioni_Id");

                    b.ToTable("RegjistriAuditimit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.SesioniPerdoruesit", b =>
                {
                    b.Property<string>("Sesioni_Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Sesioni_Id");

                    b.Property<string>("AdresaIP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("AdresaIP");

                    b.Property<DateTime>("AktivitetiI_Fundit")
                        .HasColumnType("TEXT")
                        .HasColumnName("AktivitetiI_Fundit");

                    b.Property<string>("ArsyejaPerfundimit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ArsyejaPerfundimit");

                    b.Property<bool>("Eshte_Aktiv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Eshte_Aktiv");

                    b.Property<DateTime>("Filluar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Filluar_Me");

                    b.Property<int?>("Kohezgjatja_Minuta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Kohezgjatja_Minuta");

                    b.Property<int>("NumriVeprimeve")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumriVeprimeve");

                    b.Property<string>("Perdoruesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Perdoruesi");

                    b.Property<DateTime?>("Perfunduar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Perfunduar_Me");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserAgent");

                    b.HasKey("Sesioni_Id");

                    b.HasIndex("Eshte_Aktiv");

                    b.HasIndex("Filluar_Me");

                    b.HasIndex("Perdoruesi");

                    b.ToTable("SesionetPerdoruesve");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.ShpenzimiTransportit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CmimiPerNjesi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPerditesimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrijuarNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlojiTransportit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NjesiaMatese")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerditesoPrejNga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shenime")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendiDestinacionit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendiOrigjines")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Aktiv");

                    b.HasIndex("LlojiTransportit");

                    b.HasIndex("VendiDestinacionit");

                    b.HasIndex("VendiOrigjines");

                    b.ToTable("ShpenzimetTransportit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.TabelaCustom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmriTabeles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EshteAktive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KrijuarMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrijuarNga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PerditesomMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pershkrimi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelatCustom");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bashkangjitje")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Bashkangjitje");

                    b.Property<string>("Cmimi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Cmimi");

                    b.Property<string>("EmeriBashkangjitjes")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("EmeriBashkangjitjes");

                    b.Property<string>("EmriProduktit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EmriProduktit");

                    b.Property<bool>("Eshte_Aktiv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Eshte_Aktiv");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Kategoria");

                    b.Property<string>("Kodi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Kodi");

                    b.Property<string>("KodiProduktit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("KodiProduktit");

                    b.Property<string>("Komentet")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Komentet");

                    b.Property<DateTime>("Krijuar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Krijuar_Me");

                    b.Property<string>("Krijuar_Nga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Krijuar_Nga");

                    b.Property<DateTime?>("Modifikuar_Me")
                        .HasColumnType("TEXT")
                        .HasColumnName("Modifikuar_Me");

                    b.Property<string>("Modifikuar_Nga")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Modifikuar_Nga");

                    b.Property<string>("Njesia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Njesia");

                    b.Property<string>("Origjina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Origjina");

                    b.Property<string>("Pariteti")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Pariteti");

                    b.Property<string>("Pershkrimi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Pershkrimi");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Valuta");

                    b.Property<decimal>("VleraDoganore")
                        .HasColumnType("TEXT")
                        .HasColumnName("VleraDoganore");

                    b.HasKey("Id");

                    b.HasIndex("Eshte_Aktiv");

                    b.HasIndex("Kategoria");

                    b.HasIndex("Kodi");

                    b.HasIndex("Origjina");

                    b.ToTable("VleratProdukteve");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cmimi = "1.20 ; 1.45",
                            EmriProduktit = "Tepsi alumini",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7615",
                            KodiProduktit = "7615",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi alumini 0.8mm me dim: 30cm ; 32cm",
                            Valuta = "EUR",
                            VleraDoganore = 1.20m
                        },
                        new
                        {
                            Id = 2,
                            Cmimi = "2.70",
                            EmriProduktit = "Viça",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "0102",
                            KodiProduktit = "0102-01",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "TE NDRYSHME",
                            Pariteti = "DAT",
                            Pershkrimi = "Viça (gjedhet femra që nuk kanë pjellë, mshqerra)",
                            Valuta = "EUR",
                            VleraDoganore = 2.70m
                        },
                        new
                        {
                            Id = 3,
                            Cmimi = "2.40",
                            EmriProduktit = "Dema",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "0102",
                            KodiProduktit = "0102-02",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "TE NDRYSHME",
                            Pariteti = "DAT",
                            Pershkrimi = "Dema per therje me peshe mbi 160 kg",
                            Valuta = "EUR",
                            VleraDoganore = 2.40m
                        },
                        new
                        {
                            Id = 4,
                            Cmimi = "1.50",
                            EmriProduktit = "Lopet",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "0102",
                            KodiProduktit = "0102-03",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "TE NDRYSHME",
                            Pariteti = "DAT",
                            Pershkrimi = "Lopet per therje",
                            Valuta = "EUR",
                            VleraDoganore = 1.50m
                        },
                        new
                        {
                            Id = 5,
                            Cmimi = "2.50",
                            EmriProduktit = "Tepsi e zezë",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-01",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi e zezë e emajluar me dim:40 cm",
                            Valuta = "EUR",
                            VleraDoganore = 2.50m
                        },
                        new
                        {
                            Id = 6,
                            Cmimi = "2.50 ; 3.20",
                            EmriProduktit = "Tepsi e zezë me lule",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-02",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi e zezë e emajluar(me lule) dim: 40cm ; 42 cm",
                            Valuta = "EUR",
                            VleraDoganore = 2.50m
                        },
                        new
                        {
                            Id = 7,
                            Cmimi = "1.50 ; 1.85 ; 2.30",
                            EmriProduktit = "Tepsi e zezë emajluara",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-03",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi e zezë e emajluara dim :34 cm;36 cm;38cm",
                            Valuta = "EUR",
                            VleraDoganore = 1.50m
                        },
                        new
                        {
                            Id = 8,
                            Cmimi = "3.00 ; 3.50",
                            EmriProduktit = "Tepsi teflon",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-04",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi teflon me dim: 30cm;32cm",
                            Valuta = "EUR",
                            VleraDoganore = 3.00m
                        },
                        new
                        {
                            Id = 9,
                            Cmimi = "3.80 ; 4.80",
                            EmriProduktit = "Tepsi teflon",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-05",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi teflon me dim: 34cm ;36cm",
                            Valuta = "EUR",
                            VleraDoganore = 3.80m
                        },
                        new
                        {
                            Id = 10,
                            Cmimi = "2.70",
                            EmriProduktit = "Tepsi metalike",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-06",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Kompleti",
                            Origjina = "CN",
                            Pariteti = "EXW",
                            Pershkrimi = "Tepsi metalike 1/3 (28cm;32cm;36cm)",
                            Valuta = "EUR",
                            VleraDoganore = 2.70m
                        },
                        new
                        {
                            Id = 11,
                            Cmimi = "4.50 ;5.00",
                            EmriProduktit = "Tepsi teflon",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-07",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi teflon me dim: 38cm; 40cm",
                            Valuta = "EUR",
                            VleraDoganore = 4.50m
                        },
                        new
                        {
                            Id = 12,
                            Cmimi = "1.50 ; 1.60 ; 1.85",
                            EmriProduktit = "Tepsi e zezë emajluar",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-08",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi e zezë e emajluar me dim. 34 cm ; 36 cm ; 38cm",
                            Valuta = "EUR",
                            VleraDoganore = 1.50m
                        },
                        new
                        {
                            Id = 13,
                            Cmimi = "1.20 ; 1.30 ; 1.50",
                            EmriProduktit = "Tepsi e zezë emajluar",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "7323",
                            KodiProduktit = "7323-09",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Tepsi e zezë e emajluar dim;28cm ;30cm ; 32cm",
                            Valuta = "EUR",
                            VleraDoganore = 1.20m
                        },
                        new
                        {
                            Id = 14,
                            Cmimi = "",
                            EmriProduktit = "QUMESHT PLUHUR A",
                            Eshte_Aktiv = true,
                            Kategoria = "Çmimi nga Bursa",
                            Kodi = "0402",
                            KodiProduktit = "0402-01",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "TON",
                            Origjina = "FR",
                            Pariteti = "EXW",
                            Pershkrimi = "QUMESHT PLUHUR A / DRY-MILK-PW-NED",
                            Valuta = "EUR",
                            VleraDoganore = 0m
                        },
                        new
                        {
                            Id = 15,
                            Cmimi = "",
                            EmriProduktit = "QUMESHT PLUHUR H",
                            Eshte_Aktiv = true,
                            Kategoria = "Çmimi nga Bursa",
                            Kodi = "0402",
                            KodiProduktit = "0402-02",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "TON",
                            Origjina = "FR",
                            Pariteti = "EXW",
                            Pershkrimi = "QUMESHT PLUHUR H / DRY-MILK-PW-EDI",
                            Valuta = "EUR",
                            VleraDoganore = 0m
                        },
                        new
                        {
                            Id = 16,
                            Cmimi = "0.45",
                            EmriProduktit = "Patate",
                            Eshte_Aktiv = true,
                            Kategoria = "Pemë-Perime",
                            Kodi = "0701",
                            KodiProduktit = "0701",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Patate te reja",
                            Valuta = "EUR",
                            VleraDoganore = 0.45m
                        },
                        new
                        {
                            Id = 17,
                            Cmimi = "1.25",
                            EmriProduktit = "Litar-spango",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "5607",
                            KodiProduktit = "5607",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "CN",
                            Pariteti = "EXW",
                            Pershkrimi = "Litar-spango",
                            Valuta = "EUR",
                            VleraDoganore = 1.25m
                        },
                        new
                        {
                            Id = 18,
                            Cmimi = "7.20",
                            EmriProduktit = "Perde sintetike",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "6005",
                            KodiProduktit = "6005-01",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "CN",
                            Pariteti = "EXW",
                            Pershkrimi = "Perde sintetike te firmave te njohura",
                            Valuta = "EUR",
                            VleraDoganore = 7.20m
                        },
                        new
                        {
                            Id = 19,
                            Cmimi = "12.00",
                            EmriProduktit = "Perde sintetike",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "6005",
                            KodiProduktit = "6005-02",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "KG",
                            Origjina = "TR",
                            Pariteti = "DAT",
                            Pershkrimi = "Perde sintetike te firmave te njohura",
                            Valuta = "EUR",
                            VleraDoganore = 12.00m
                        },
                        new
                        {
                            Id = 20,
                            Cmimi = "0.35",
                            EmriProduktit = "Cadra shiu",
                            Eshte_Aktiv = true,
                            Kategoria = "Tjera",
                            Kodi = "6601",
                            KodiProduktit = "6601",
                            Krijuar_Me = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Krijuar_Nga = "Admin",
                            Njesia = "Copë",
                            Origjina = "CN",
                            Pariteti = "EXW",
                            Pershkrimi = "Cadra shiu",
                            Valuta = "EUR",
                            VleraDoganore = 0.35m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.GlobalPrintFormat", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.FormatPrintimi", "FormatPrintimi")
                        .WithMany()
                        .HasForeignKey("FormatPrintimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormatPrintimi");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.HistoriaVlerave", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", "VleraProduktit")
                        .WithMany("HistoriaVlerave")
                        .HasForeignKey("VleraProduktit_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VleraProduktit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.ImazhetProduktit", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", "VleraProduktit")
                        .WithMany()
                        .HasForeignKey("VleraProduktit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VleraProduktit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Komenti", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", "VleraProduktit")
                        .WithMany("KomentList")
                        .HasForeignKey("VleraProduktitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VleraProduktit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.KomentiDeges", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", "VleraProduktit")
                        .WithMany()
                        .HasForeignKey("VleraProduktit_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VleraProduktit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.NdryshimiTransportit", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.ShpenzimiTransportit", "ShpenzimiTransportit")
                        .WithMany("Ndryshimet")
                        .HasForeignKey("ShpenzimiTransportit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShpenzimiTransportit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.Dega", "Dega")
                        .WithMany("Perdoruesit")
                        .HasForeignKey("Dega_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dega");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.PrintAuditLog", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.FormatPrintimi", "FormatPrintimi")
                        .WithMany()
                        .HasForeignKey("FormatPrintimiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FormatPrintimi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KosovaDoganaModerne.Modelet.Entitetet.Perdoruesi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.Dega", b =>
                {
                    b.Navigation("Perdoruesit");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.ShpenzimiTransportit", b =>
                {
                    b.Navigation("Ndryshimet");
                });

            modelBuilder.Entity("KosovaDoganaModerne.Modelet.Entitetet.VleraProduktit", b =>
                {
                    b.Navigation("HistoriaVlerave");

                    b.Navigation("KomentList");
                });
#pragma warning restore 612, 618
        }
    }
}
